default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: protospace_42612_development

test:
  <<: *default
  database: protospace_42612_test

# ★本番はDATABASE_URLをRenderから受け取る
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
